#!/usr/bin/env bash
# This Bash script automates the configuration of domain zones and provides detailed
# information about specified subdomains. It fulfills specific requirements, including
# adding predefined subdomains and pointing them to designated IP addresses. The script
# takes two arguments - the domain name to be audited and an optional subdomain for more
# granular information. The output includes details about the subdomain's record type and
# destination. The script adheres to best practices, using AWK and at least one Bash
# function while ignoring certain edge cases, making it a robust tool for domain
# configuration and analysis.

domain_information () {
    line=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $line" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 1 ]
then
  domain_information "$1" "www"
  domain_information "$1" "lb-01"
  domain_information "$1" "web-01"
  domain_information "$1" "web-02"
elif [ "$#" == 2 ]
then
  domain_information "$1" "$2"
fi
