#!/usr/bin/env bash
# Script that transfers a file from our client to a server:

msg="Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"

if [ "$#" -lt 4 ]; then
    echo "$msg"
    exit 1
fi
scp_args=(-o StrictHostKeyChecking=no)
if [ "$4" ]; then
    scp_args+=(-i "$4")
fi
scp "${scp_args[@]}" "$1" "$3@$2:~" && echo "File transferred successfully to $3@$2:~/"
