#!/usr/bin/env bash
# Installs Nginx on web-01

server_name="web-01"
server_ip="100.25.34.196"

sudo apt-get update

sudo apt-get install -y nginx

sudo sh -c "echo \"server {
    listen 80;
    server_name $server_name;

    location / {
        echo \\\"HTTP/1.1 200 OK\\n\\nHello World!\\\" | sudo tee /var/www/html/index.html > /dev/null;
    }
}\" > /etc/nginx/sites-available/default"

sudo service nginx restart

echo "Nginx installed and configured. Now listening on $server_ip:80 with server name $server_name"
