#!/usr/bin/env bash
# Installs Nginx on web-o1

apt-get update
apt-get install -y nginx
echo "Holberton School" > /var/www/html/index.html
service nginx start
update-rc.d nginx defaults
echo "Nginx installed and configured successfully. Listening on port 80."
