#!/usr/bin/env bash
#Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page.

./1-install_nginx_web_server
nginx_conf="/etc/nginx/sites-available/default"
sed -i '/server_name _;/a \ \ \ \ error_page 404 /404.html;\n \ \ \ \ location = /404.html {\n \ \ \ \ \ \ \ \ root /var/www/html;\n \ \ \ \ \ \ \ \ internal;\n \ \ \ \ }' "$nginx_conf"
echo "Ceci n'est pas une page." > /var/www/html/404.html
service nginx restart
echo "Nginx custom 404 page configured successfully."
