#!/usr/bin/env bash
#Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page.

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
sudo sed -i '/listen 80 default_server;/a \    location /redirect_me {\n        return 301 https://www.google.com/;\n    }' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html > /dev/null
sudo sed -i '/listen 80 default_server;/a \    error_page 404 /custom_404.html;' /etc/nginx/sites-available/default
sudo service nginx restart
