#!/usr/bin/env bash

# Script to find out what’s keeping your Ubuntu container’s
# nginx installation from listening on port 80

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
