#!/usr/bin/env bash
# Displays message and sleeps for 2 seconds between each iteration
# Displays I am invincible!!! when receiving a SIGTERM signal

trap 'echo "I am invincible!!!"' SIGTERM
while true
do
    echo "To infinity and beyond"
    sleep 2
done
