#!/usr/bin/env bash
# Displays contents of file in path /etc/passwd

file_path="/etc/passwd"

while IFS=: read -r username _ uid _ _ home _; do
    echo "Username: $username"
    echo "User ID: $uid"
    echo "Home Directory: $home"
done < "$file_path"
