#!/usr/bin/env bash
# Displays a story based on the content of the /etc/passwd

file_path="/etc/passwd"

while IFS=: read -r username _ uid gid info home shell; do
    echo "The user $username is part of the $gid gang,"
    echo "lives in $home and rides $shell."
    echo "User ID's place is protected by the passcode $info,"
    echo "more info about the user here: $uid INFO"
    echo ""
done < "$file_path"
