#!/usr/bin/env bash
# Displays a story based on the content of the /etc/passwd

path="/etc/passwd"

while IFS= read -r line; do
    username="$(echo "$line" | cut -d":" -f1)"
    group_id="$(echo "$line" | cut -d":" -f4)"
    home_directory="$(echo "$line" | cut -d":" -f6)"
    user_shell="$(echo "$line" | cut -d":" -f7)"
    user_id="$(echo "$line" | cut -d":" -f3)"
    passcode="$(echo "$line" | cut -d":" -f7)"  # Using field 7 for shell
    additional_info="$(echo "$line" | cut -d":" -f5)"

    echo "The user ${username} is part of the ${group_id} gang, lives in ${home_directory} and rides ${user_shell}. ${user_id}'s place is protected by the passcode ${passcode}, more info about the user here: ${additional_info}"
done < "$path"
