#!/usr/bin/env bash
# Disaplying Best school then hi using while and if

#!/bin/bash

count=0

while [ $count -lt 10 ]; do
    echo "Best School"

    if [ $count -eq 8 ]; then
        echo "Hi"
    fi

    ((count++))
done
