#!/usr/bin/env bash
#script that loops from 1 to 10 implementing the while, if, elif and else

count=1

while [ $count -le 10 ]; do
    if [ $count -eq 4 ]; then
        echo "Bad Luck"
    elif [ $count -eq 8 ]; then
        echo "Good Luck"
    else
        echo "Best School"
    fi

    ((count++))
done
