#!/usr/bin/ env bash
# Block all incoming traffic ecxpet on ports 22, 80 and 443

sudo apt install ufw
sudo ufw default deney incoming
sudo ufw default allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw enable
sudo ufw status verbose
